#!/bin/bash

program=$(basename $0)
service=$1
if [ $# -lt 1 ]
then
  echo "Usage: $program service-regex [stackname] [command]"
  exit 1
fi

name=${2:-unstable-ecscluster-support}
shift
shift
hosts=$(aws ec2 describe-instances \
  --filters Name=tag:Name,Values=$name \
  Name=instance-state-name,Values=running \
  | jq -r .Reservations[$index].Instances[].PublicDnsName)

for host in $hosts; do
  match=$(ssh $host "docker ps |grep $service")
  if [ -n "$match" ]; then
    found=$host
  fi
done
if [ -n "$found" ]; then
  echo "Service found on $found, connecting"
  ssh $found "$*"
else
  echo "Service NOT found, $service"
fi
