#!/bin/bash

name=$1
index=0
re='^[0-9]+$'
if [[ $2 =~ $re ]] ; then
  index=${2}
  shift
fi
shift
dns=$(aws ec2 describe-instances \
  --filters Name=tag:Name,Values=$name \
  Name=instance-state-name,Values=running \
  | jq -r .Reservations[$index].Instances[0].PublicDnsName)

echo "$dns"
ssh $dns $*

